# Generated by Django 4.0.5 on 2023-01-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_platformer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platformer',
        ),
    ]
